package object constants {
	val spellSchoolCodes = Map(
		'C' -> "SPELL_SCHOOL_CONJURATION",
		'G' -> "SPELL_SCHOOL_GENERAL",
		'A' -> "SPELL_SCHOOL_ABJURATION",
		'D' -> "SPELL_SCHOOL_DIVINATION",
		'E' -> "SPELL_SCHOOL_ENCHANTMENT",
		'V' -> "SPELL_SCHOOL_EVOCATION",
		'I' -> "SPELL_SCHOOL_ILLUSION",
		'N' -> "SPELL_SCHOOL_NECROMANCY",
		'T' -> "SPELL_SCHOOL_TRANSMUTATION",
		'*' -> "SPELL_SCHOOL_GENERAL"
	)

	val damageTypeConsts = Seq(
		"DAMAGE_TYPE_ALL",
		"DAMAGE_TYPE_BLUDGEONING",
		"DAMAGE_TYPE_PIERCING",
		"DAMAGE_TYPE_SLASHING",
		"DAMAGE_TYPE_MAGICAL",
		"DAMAGE_TYPE_ACID",
		"DAMAGE_TYPE_COLD",
		"DAMAGE_TYPE_DIVINE",
		"DAMAGE_TYPE_ELECTRICAL",
		"DAMAGE_TYPE_FIRE",
		"DAMAGE_TYPE_NEGATIVE",
		"DAMAGE_TYPE_POSITIVE",
		"DAMAGE_TYPE_SONIC"
	)
}